# This is a basic workflow to help you get started with Actions

# Controls when the workflow will run
name: Post welcome comment
on:
  pull_request:
    types: [opened]
permissions:
  pull-requests: write
